server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:clients
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
